### ISSUE TITLE
Second image in the how to install wiki

### ISSUE THREAD

**Issue by Dave-Wagner** [lfelipe1501/Arch-MOTD#1]
It's not huge but I just though I'd let you know that the second image references "scripts_motd.sh" when it should be referencing "update_motd.sh".

**Comment by lfelipe1501** [comment]
ok I will update this image very soon... 🔢

**Comment by lfelipe1501** [comment]
> It's not huge but I just though I'd let you know that the second image references "scripts_motd.sh" when it should be referencing "update_motd.sh".

is done in the wiki session.... 👍
